# -*- coding: utf-8 -*-
"""1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RGIhmK93e9g6fFeSD1KDyu1h8BfFJZa-
"""

#Aray operations
#program to consider a list arr=[10,20,30,40] and perform insert operations and deletion operation with 50 and 25 at position 2 respectively , delete 30 and traverse the array to fetch a number 25 is present or not.'''
# arr=[10,20,30,40] # Removed initialization from here  #program to consider a list arr=[10,20,30,40] and perform insert operations and deletion operation with 50 and 25 at position 2 respectively , delete 30 and traverse the array to fetch a number 25 is present or not.'''
arr=[10,20,30,40] # Added initialization here

#insert 50
arr.append(50)
#insert 25 at position 2
arr.insert(2,25)
#deletion of 30
arr.remove(30)

print(arr)
#traversal
for i in arr:
    print(i, end = '')
#seareching
print("\n 25 in array",25 in arr) # similar codes that can be asked in interviews

'''program to check whether the given string is palindrome or not
and count the palandromic characters whic are repeated count
str= madam
output: {'m': 2, 'a': 2, 'd':1}
str = malayalam'''
text= input("Enter a name:")
if text==text[::-1]:
    print("Palindrome")
else:
    print("Not")
freq={}
for ch in text:
    freq[ch] = freq.get(ch,0)+1
print(freq)

